//List
export const ADD_MESSAGE = "LIST/ADDMESSAGE";
export const SHOW_LOADER = "LIST/SHOW_LOADER";
export const HIDE_LOADER = "LIST/HIDE_LOADER";
export const SET_CACHE_MESSAGE = "LIST/SET_CACHE_MESSAGE";
