export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

// ?TEACH
// export const LOAD_DOCS = "TEACH/HIDE_LOADER";

//List
export const LOAD_MORE_ELEMENTS = "LIST/LOAD_MORE_ELEMENTS"
export const ADD_MESSAGE = "LIST/ADDMESSAGE";
export const SET_CACHE_MESSAGE = "LIST/SET_CACHE_MESSAGE";
export const SET_ORGANIZATIONS_INFO = "LIST/SET_ORGANIZATIONS_INFO";
// SET_ORGANIZATIONS_INFO
//TEACHMODE

export const SET_MODE = "TEACH/SET_MODE";
export const ADD_LINK = "TEACH/ADD_LINK";
// export const SEND_MESSAGE_TO_TEACHER = "TEACH/SEND_MESSAGE_TO_TEACHER"

//COMMETNS
export const LOAD_INFO_COMMENTS = 'COMMENTS/LOAD_INFO_COMMENTS'

export const UPDATE_COMMENTS = 'COMMENTS/UPDATE_COMMENTS'