export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

// ?TEACH
// export const LOAD_DOCS = "TEACH/HIDE_LOADER";

//List
export const ADD_MESSAGE = "LIST/ADDMESSAGE";
export const SET_CACHE_MESSAGE = "LIST/SET_CACHE_MESSAGE";

//TEACHMODE

export const ADD_LINK = "TEACH/ADD_LINK";
// export const SEND_MESSAGE_TO_TEACHER = "TEACH/SEND_MESSAGE_TO_TEACHER"